### PR TITLE
Registered myself

### PR DESCRIPTION
**Pull request by iampavangandhi**
Hello Maintainer,

Kindly review my pull request.

Thank You

### CODE REVIEW

**Comment by khusharth** [comment]
Hey! @iampavangandhi you have added a project that have been built before the start of the challenge. Only projects made during the challenge are counted towards the challenge. If you want to add previous projects then specify them as past projects in this file.

Also a small typo: *I am a Pavan Gandhi ...*

**Comment by iampavangandhi** [comment]
Sorry, @khusharth I don't know that the project built before is not considered. I will update my file and create a pull request again.

**Comment by iampavangandhi** [comment]
@khusharth I updated my file please have a look.

**Comment by khusharth** [comment]
@iampavangandhi no problem :). The changes look fine to me now. It will be merged soon.

**Comment by gkanishk** [comment]
Welcome on board!!!

**Pull request merged**
