### PR TITLE
Finalist Directory Added

### PR DESCRIPTION
**Pull request by arpitgupta1250**
Hi
Please accept.

### CODE REVIEW

**Comment by gkanishk** [comment]
there are conflicts inside your PR kindly resolve them

**Comment by arpitgupta1250** [comment]
How to resolve this
Please tell

**Comment by arpitgupta1250** [comment]
First i have added in participant and it is merged by you.
Than i have updated in the finalist folder same content.

**Comment by arpitgupta1250** [comment]
Please check now

**Pull request merged**
