### PR TITLE
registeringAmarKumar

### PR DESCRIPTION
**Pull request by amarcahturvedi16**
hello maintainer,
please approve my PR. Thank you so much for letting such an awesome opportunity.

### CODE REVIEW

**Comment by amarcahturvedi16** [comment]
mistakenly created new one rather than updating the existing

**Comment by amarcahturvedi16** [comment]
older repostitory got deleted. apologies for in-convinience

**Comment by gkanishk** [comment]
The **first round** of registrations are closed and hence we are not accepting this **PR** right now. Stay tuned for further updates on [t.me/tanaypratap](t.me/tanaypratap) and apply again when the registration re-opens in a few days. This PR might not be considered for that round or will be considered only at the end. Therefore, it would be better to raise a fresh PR when the registration announcement is made.

**Comment by amarcahturvedi16** [comment]
Actually I have raised PR earlier #60. But there was some issue, rather than correcting it  I deleted that repo mistakenly. So raised this new PR with new repo. Please let me know if it is possible to merge this.
Or will raise a new PR tomorrow again as per Tanay's guidelines.

**Pull request merged**
