### PR TITLE
Registration Nitesh Narang

### PR DESCRIPTION
**Pull request by theniteshnarang**
Hey TeamTanay,

You are doing wonderful job for people like us for no personal benefit, Thank you for creating this challenge, i encourage you to do more such sub-challenges in it, So people would be more committed in completing the task of learning react and react native.

### CODE REVIEW

**Comment by rutikwankhade** [comment]
Fix typos 
line 10, afcourse as of course
line 17 chalange as challenge
also, read carefully and fix typos

**Comment by gkanishk** [comment]
Hey @theniteshnarang ,
I just reviewed your **PR** and found that you did something wrong.
You have done changes inside **package.lock.json** file kindle resolve and make sure the file remains unchanged and **file changed** count shows only 1.
You have to create only **index.md** file.

**Comment by theniteshnarang** [comment]
> Hey @theniteshnarang ,
> I just reviewed your **PR** and found that you did something wrong.
> You have done changes inside **package.lock.json** file kindle resolve and make sure the file remains unchanged and **file changed** count shows only 1.
> You have to create only **index.md** file.

Actually its nothing, i just checked "the viewed checkbox "(across package.lock.json) and then unchecked it, So therefore it shows the 2 files changed.

**Comment by gkanishk** [comment]
You don't have to delete the package.lock.json file that has to be but without any changes,
Kindly resolve

**Comment by theniteshnarang** [comment]
Hey Maintainer,
I deleted package-lock.json, will it rectify it now?, or do i have to make new branch and send the PR again.

**Comment by theniteshnarang** [comment]
> You don't have to delete the package.lock.json file that has to be but without any changes,
> Kindly resolve

I don't know how to resolve, because i haven't done any changes in it. Should i make new branch and upload it again.

**Comment by theniteshnarang** [comment]
> > You don't have to delete the package.lock.json file that has to be but without any changes,
> > Kindly resolve
> 
> I don't know how to resolve, because i haven't done any changes in it. Should i make new branch and upload it again.

Hey Maintainer,
I resolved the thing in package-lock.json, kindly please check and accept My PR.
Thank you for assisting me.

**Pull request merged**
