### PR TITLE
New Participant Ritvik | @ritvyk

### PR DESCRIPTION
**Pull request by Ritvyk**
Hey Maintainers & Tanay Pratap Sir , Really excited about this challenge, it is something that will help me to the truth to myself whether I brag about my skills in web development or it is something that is true within me.
I hope you will accept my PR.
Thanks for making this challenge, Sir!

### CODE REVIEW

**Comment by gkanishk** [comment]
Kindly do changes inside your file only and revert the changes

**Comment by Ritvyk** [comment]
Hey @gkanishk I think no changes were made , I have compared those files it says no change , I think we can go with the merge.

**Comment by gkanishk** [comment]
Hey @Ritvyk ,
There are still some changes shown
image
Kindly resolve or raise a fresh **PR**

**Comment by surajy93** [comment]
> Hey @gkanishk I think no changes were made , I have compared those files it says no change , I think we can go with the merge.

upload this user file content/participants/ttjc@viveksonar /index.md then check file change.
I think mistakenly you have deleted the file of that user.

**Comment by gkanishk** [comment]
Closing this **PR** as getting no response kindly generate a new **PR**

**Pull request closed without merging**
