### PR TITLE
registering Bibin-Antony

### PR DESCRIPTION
**Pull request by Bibin-Antony**
Hey maintainer!

I hope you are well. kudos on the job. I hope i get accepted.

### CODE REVIEW

**Comment by Bibin-Antony** [comment]
I hope to see my name. thank you.

**Comment by gkanishk** [comment]
hey @Bibin-Antony you have done changes inside package.lock.json and package.json kindly revert that and do changes only inside index.md file

**Comment by Bibin-Antony** [comment]
dear collaborator,
be kind enough to tell me how to revert the changes. i deleted package.lock.json and package.json to install npm cause with that it was not downloading. i found that solution on google.

**Comment by gkanishk** [comment]
You don't need to delete the files simply see what were the changes done like any addition any removal or change in the indentation.

**Pull request merged**
