### PR TITLE
Demoparticipant/registration update

### PR DESCRIPTION
**Pull request by Cvmsingh**
Hey SIR,
I will updated , you are doing a great job. Kindly accept my request.

### CODE REVIEW

**Comment by gkanishk** [comment]
The **first round** of registrations are closed and hence we are not accepting this **PR** right now. Stay tuned for further updates on [t.me/tanaypratap](t.me/tanaypratap) and apply again when the registration re-opens in a few days. This PR might not be considered for that round or will be considered only at the end. Therefore, it would be better to raise a fresh PR when the registration announcement is made.

**Comment by Cvmsingh** [comment]
sir i already registration in top -50 , now i only update my title : demo
participant because you mail me to edit it .
Thank you

**Comment by gkanishk** [comment]
OK will review it

**Comment by Cvmsingh** [comment]
it's  done sir

**Pull request merged**
