### PR TITLE
Create index.md

### PR DESCRIPTION
**Pull request by ishita303**

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @ishita303 ,
There are some conflicts inside your **PR** please resolve.

**Comment by ishita303** [comment]
Please ignore this commit, I was looking for my index.md, was unable to find, so gave this create request

**Comment by ishita303** [comment]
Sure will check it out.

**Comment by ishita303** [comment]
Hi, you might have closed the right pull request.

This is the older one-
https://github.com/tanaypratap/teamtanay.jobchallenge.dev/blob/master/content/participants/ttjc%40ishita303/index.md

Can I update this one now, or what should I do?

Let me know, Thanks.

**Pull request closed without merging**
