### PR TITLE
Registering Omkar.

### PR DESCRIPTION
**Pull request by OmkarGeedh**

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey Omkar ,
Reviewed your PR everything is fine so don't worry just a small mistake you have not used proper markdown due to which your LinkedIn profile is not visible as hyperlink 
image
Kindly resolve this.

**Comment by OmkarGeedh** [comment]
Please check it again, I have fixed this.

**Comment by gkanishk** [comment]
Use proper markdown syntax [ ](link)

**Comment by gkanishk** [comment]
Please use proper markdown [click](link)

**Comment by OmkarGeedh** [comment]
[LinkedIn](https://www.linkedin.com/in/omkar-geedh-2ba538152)
is this a correct way?

**Comment by OmkarGeedh** [comment]
Done Please check

**Comment by gkanishk** [comment]
Perfect

**Comment by OmkarGeedh** [comment]
Thank you for your effords

**Pull request merged**
