### PR TITLE
Registered myself

### PR DESCRIPTION
**Pull request by knightcube**
Hi. This looked like a fun challenge to be a part of. Couldn't resist myself being a part of it. I will create more projects and write articles. Thanks for this initiative.

### CODE REVIEW

**Comment by khusharth** [comment]
hey @knightcube you have added projects that have been built before the start of the challenge. Only projects made during the challenge are counted towards the challenge. If you want to add previous projects then specify them as past projects in this file. Same for your last blog.

**Comment by knightcube** [comment]
> 
> 
> hey @knightcube you have added projects that have been built before the start of the challenge. Only projects made during the challenge are counted towards the challenge. If you want to add previous projects then specify them as past projects in this file. Same for your last blog.

I have made the  corresponding changes. Kindly let me know if there are any other problems to resolve.

**Comment by khusharth** [comment]
@knightcube sorry for the inconvenience but we have decided not to keep the past projects and blogs in the index.md file. Please remove them and your PR will be merged.

**Comment by knightcube** [comment]
Do I need to remove the "More links" section too?

**Comment by khusharth** [comment]
@knightcube That is fine.

**Comment by knightcube** [comment]
Hi. I have made the changes. Kindly merge the PR.

**Pull request merged**
