### PR TITLE
registering TheDemonDante

### PR DESCRIPTION
**Pull request by TheDemonDante**
Hey there!

Kindly accept request.

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @TheDemonDante  ,
I just reviewed your **PR** and noticed you did everything the **wrong** way.
You have done changes is wrong to file you need to create a new directory with your username and put an **index.md** file with your details
This is how it would look like:
image
Kindly refer to the [Youtube Live](https://www.youtube.com/watch?v=QzjgBj9oaAA&t=850s) for the correct way.

**Comment by TheDemonDante** [comment]
Hello sir,

Firstly I'd like to apologise for the late reply.
Thank you for reaching out individually and pointing the mistakes. Both VCS
and GitHub are new to me and I'm not able to figure out what the mistake is
from my side.(I did check the registration video a couple of times)

I'll learn web development without participating in the jobchallenge.
Ignore my application.


Thanking you
Manish

**Comment by gkanishk** [comment]
You are simply stepping back and that's not good, you have the resources to
learn just google what problem are you facing and try to resolve it. This
challenge is one time opportunity .It's like now or never,I hope you won't
disappoint.
Happy Coding✌️✌️

**Comment by TheDemonDante** [comment]
Hello Sir,

I want to clarify. Did you just correct my mistake and include me in the
challenge?

**Comment by gkanishk** [comment]
Yes I resolved the issues with your **PR** you can check your name on the [list](https://2020.teamtanay.jobchallenge.dev/participants)

**Comment by TheDemonDante** [comment]
I don't know what to say. I'm  grateful for your help.

Thank you so much

**Comment by gkanishk** [comment]
Now that your **PR** is merged kindly update with proper details.

**Pull request merged**
