### PR TITLE
Ashish0077/registration update

### PR DESCRIPTION
**Pull request by Ashish0077**

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @Ashish0077 ,
Just reviewed your **PR** everything looks good but there's a sight error in your PR you have made changes inside **.vscode/settings.json** file please undo the changes and resolve.

**Comment by Ashish0077** [comment]
@gkanishk
changes reverted of vscode/settings.json

**Comment by gkanishk** [comment]
There are still some issue, make sure the "*file changed** shows count 1

**Comment by Ashish0077** [comment]
@gkanishk
Changes reverted
extra commits squashed!!

**Comment by gkanishk** [comment]
Cool will review it

**Pull request merged**
