### PR TITLE
Registering PremanandChowdhury

### PR DESCRIPTION
**Pull request by PremanandChowdhury**
Hey  mentors!!
Kindly accept my PR.

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @PremanandChowdhury kindly revert the changes inside other files and do changes inside index.md file only

**Comment by PremanandChowdhury** [comment]
Please can you mention the problem, Particularly?

**Comment by PremanandChowdhury** [comment]
Please, can you tell me what has been the problem.
Thank you.

**Comment by gkanishk** [comment]
You have done changes inside package.json file

**Comment by PremanandChowdhury** [comment]
sir, i am stuck. I work on npm and yarn i installed for uploading this commit and it showed there are two lock files available.
So, i deleted the npm lock file.

**Comment by gkanishk** [comment]
Clone again and use either yarn or npm, use of yarn preferred

**Comment by PremanandChowdhury** [comment]
Should i create a pull request again will that be fine?

**Pull request closed without merging**
