### PR TITLE
Adding a list page for mentors

### PR DESCRIPTION
**Pull request by ashwin-g-g**
Added a mentorslist.js file, made few changes in mentor writeup. Please review if I've done it right.

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @tanaypratap ,
A gentle reminder the review for this PR is pending!

**Comment by ashwin-g-g** [comment]
A gentle reminder @tanaypratap

**Comment by tanaypratap** [comment]
image

**Comment by gkanishk** [comment]
Created page generator inside #511 can have a look @ashwin-g-g @tanaypratap

**Pull request closed without merging**
