### PR TITLE
Updated folder to the finalist directory

### PR DESCRIPTION
**Pull request by meghnavarma0**
Hey Maintainers,

You've been great throughout the challenge. 

Thank You for your efforts!

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @meghnavarma0 ,
Your third [blog](https://backtobasics.vercel.app/parameters-arguments/) is showing deployment error can you have a look!
image

**Comment by meghnavarma0** [comment]
Thanks @gkanishk for pointing that out! I have fixed the typo. Please it check now!

**Comment by gkanishk** [comment]
Hey, @meghnavarma0 last feedback some of your app show title as "React App" kindly change them.

**Comment by meghnavarma0** [comment]
Yeah Sure! Thanks @gkanishk !!

**Pull request merged**
