### PR TITLE
registering Saad Ahmed

### PR DESCRIPTION
**Pull request by darkside550**
Hello Maintainer!

Kindly accept my request, interesting projects await!

Thank You!

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @darkside550 ,
Just reviewed your `PR` and found that you have done changes inside `package.json` `package-lock.json` kindly revert the changes inside those files and make sure **file changed** count shows 1.

**Comment by gkanishk** [comment]
Kindly resolve the issues

**Comment by gkanishk** [comment]
Hey @darkside550 ,
KIndly resolve the PR

**Comment by darkside550** [comment]
> Hey @darkside550 ,
> KIndly resolve the PR

Hello!
Issues Resolved

**Pull request merged**
