### PR TITLE
updated projects and blogs

### PR DESCRIPTION
**Pull request by cmcodes1**
I have completed 5 projects and 3 blogs. Kindly accept my PR.

### CODE REVIEW

**Comment by gkanishk** [comment]
Kindly add the finalist file.

**Comment by cmcodes1** [comment]
@gkanishk Yeah! I will do that. But, don't we need to first get our participants PR accepted and then do a PR for finalist?

**Comment by gkanishk** [comment]
You can raise both at once

**Comment by cmcodes1** [comment]
Did as you asked. PR #1127

**Comment by gkanishk** [comment]
Raised new PR #1127

**Pull request closed without merging**
