### PR TITLE
registering shubhamchopade

### PR DESCRIPTION
**Pull request by shubhamchopade**
Hey maintainer,

I am glad you took up this initiative. Kindly accept my request.

### CODE REVIEW

**Comment by gkanishk** [comment]
hey @shubhamchopade ,
you have done changes inside `yarn.lock` file kindly revert those changes and do changes inside your `index.md` file only.
Regards,
Kanishk

**Comment by shubhamchopade** [comment]
I have reverted back the yarn.lock file. Kindly see if its correct now. Thank you.

**Comment by gkanishk** [comment]
Welcome on-board!!

**Comment by shubhamchopade** [comment]
Hey! Thanks a lot 👍

**Pull request merged**
