### PR TITLE
Registering again with few corrections.

### PR DESCRIPTION
**Pull request by simscool1**
Kindly accept the request. 
Keen to know about more corrections.

### CODE REVIEW

**Comment by khusharth** [comment]
Hey! @simscool1 You have made changes in many other participants files. Only changes done in your **index.md** are allowed. Please revert them.

**Comment by simscool1** [comment]
> Hey! @simscool1 You have made changes in many other participants files. Only changes done in your **index.md** are allowed. Please revert them.

Thank You. I will do it now.

**Comment by simscool1** [comment]
> > Hey! @simscool1 You have made changes in many other participants files. Only changes done in your **index.md** are allowed. Please revert them.
> 
> Thank You. I will do it now.

But how to do that?

**Comment by khusharth** [comment]
From what i can see is you have renamed 9 participants file without any changes. Can i know what were you trying to achieve through this commit? The commit does not contain anything related to your profile?

**Comment by gkanishk** [comment]
Hey @simscool1 ,
Can you open a new fresh **PR** as you have done number of changes and you are unable to cope with the issue!!

**Comment by simscool1** [comment]
> From what i can see is you have renamed 9 participants file without any changes. Can i know what were you trying to achieve through this commit? The commit does not contain anything related to your profile?

In order to change my name which I misspelled earlier, I did that by mistake. I reverted few. But, I am unable to revert some commits.

**Comment by simscool1** [comment]
> Hey @simscool1 ,
> Can you open a new fresh **PR** as you have done number of changes and you are unable to cope with the issue!
> use git pull to update the local repository and after that do the changes.

Yes I can.

**Pull request closed without merging**
