### PR TITLE
registering The7th-Hokage

### PR DESCRIPTION
**Pull request by The7th-Hokage**
Hey maintainer, 
I surely am a bit late to register for the challenge, but I was following all of Tanay's lives, posts, telegram group regarding this challenge. I ensure I won't let you down if you accept my pull request and give me this once in a lifetime opportunity. 
Thank you!

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @The7th-Hokage ,
Just reviewed your **PR** and found some major issues in your **PR** you have done changes in other files like package.json and package.lock.json kindly revert the changes in those files and do changes only inside your index.md file.

**Comment by surajy93** [comment]
> Hey maintainer,
> I surely am a bit late to register for the challenge, but I was following all of Tanay's lives, posts, telegram group regarding this challenge. I ensure I won't let you down if you accept my pull request and give me this once in a lifetime opportunity.
> Thank you!

You can fix this issue by just replacing the package.json and yarn.lock with the new one you can download this from the given link and https://github.com/tanaypratap/teamtanay.jobchallenge.dev/.

**Comment by The7th-Hokage** [comment]
> Hey @The7th-Hokage ,
> Just reviewed your **PR** and found some major issues in your **PR** you have done changes in other files like package.json and package.lock.json kindly revert the changes in those files and do changes only inside your index.md file.

Okay sir, Sorry. I am new to git, I'll do it again and then I have to just push or create a pull request again?

**Comment by The7th-Hokage** [comment]
> > Hey maintainer,
> > I surely am a bit late to register for the challenge, but I was following all of Tanay's lives, posts, telegram group regarding this challenge. I ensure I won't let you down if you accept my pull request and give me this once in a lifetime opportunity.
> > Thank you!
> 
> You can fix this issue by just replacing the package.json and yarn.lock with the new one you can download this from the given link and https://github.com/tanaypratap/teamtanay.jobchallenge.dev/.

Okay, thank you, sir!

**Comment by The7th-Hokage** [comment]
> Hey @The7th-Hokage ,
> Just reviewed your **PR** and found some major issues in your **PR** you have done changes in other files like package.json and package.lock.json kindly revert the changes in those files and do changes only inside your index.md file.

Sir, I have downloaded those 3 files from Github and replaced them in my local repository. Then I have committed using Github desktop and then there was an option of push origin. I have done that. Is this correct?

**Pull request merged**
