### PR TITLE
registering namancdr

### PR DESCRIPTION
**Pull request by namancdr**
hey maintainer

You're doing a great job, kindly accept my request.

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @namancdr  ,
I just reviewed your **PR** and noticed you did everything the **wrong** way.
You have done changes is wrong to file you need to create a new directory with your username and put an **index.md** file with your details
This is how it would look like:
image
Kindly refer to the [Youtube Live](https://www.youtube.com/watch?v=QzjgBj9oaAA&t=850s) for the correct way.

**Comment by namancdr** [comment]
Can i correct it now ?

**Comment by gkanishk** [comment]
Clone the repo again and do a PR

**Comment by namancdr** [comment]
please check it again, i have fixed this.

**Comment by gkanishk** [comment]
it's fine now

**Comment by namancdr** [comment]
😁

**Pull request merged**
