### PR TITLE
registering mayankgoel871

### PR DESCRIPTION
**Pull request by mayankgoel871**
Kindly accept my request.

### CODE REVIEW

**Comment by gkanishk** [comment]
There are still changes visible inside and there is no directory with your registered name so I would suggest making a fresh PR refer the youtube tutorial for proper guidance

**Comment by gkanishk** [comment]
Your **PR** has some conflict kindly resolve them.

**Comment by mayankgoel871** [comment]
Sir, i have sent a fresh pr as suggested by you in previous mail and it has
been merged. So, what should i do about this?

**Comment by gkanishk** [comment]
if its merge then close this PR

**Pull request closed without merging**
