### PR TITLE
Update index.md

### PR DESCRIPTION
**Pull request by meghnavarma0**
Hey Maintainer/s,

You're doing a great job as regards the job challenge. I've learn't a lot in the last three months. Thank You for your efforts.

### CODE REVIEW

**Comment by gkanishk** [comment]
Awesome work @meghnavarma0 !!! Where's your 3rd blog please write and add!!

**Comment by meghnavarma0** [comment]
Thanks for considering my pull-request @gkanishk !!! I've added the link to the third blog

**Comment by gkanishk** [comment]
Awesome!! Please add the finalists file also refer #935 for reference

**Comment by meghnavarma0** [comment]
Raised another PR [#1014](https://github.com/tanaypratap/teamtanay.jobchallenge.dev/pull/1014)

**Comment by gkanishk** [comment]
Merged inside #1014

**Pull request closed without merging**
