### PR TITLE
Project Update

### PR DESCRIPTION
**Pull request by chandan-kj**
Hey mentor,
I have built 2 website using MERN stack, E-commerce website and Todo-list app.
Please review my project.
Thank you

### CODE REVIEW

**Comment by Uyadav207** [comment]
mistake

## some Suggestions : 
* you should not represent your projects as a summary or a paragraph.
* Some Typos in here..(minor)  

## Reason
* The person visiting your profile will feel lethargic while reading.
* Your projects are the one to what people look at .. 
## What one can do ??

```
_description_  <Your Project Description Goes Here>

_stack_  <Your Tools and Languages stuff Goes here>

_hosted link_  <Hosted Link if any...Goes here>

_github link_  <Repository Link ... Better if the repo is Documented..>
```
That's why we were provided with the template..

Keep contributing ...
Thanks...
@Uyadav207

**Comment by chandan-kj** [comment]
Thank you for the suggestions sir

**Comment by chandan-kj** [comment]
Hey Mentor,
As per your suggestions i have made changes. Please accept my PR.
Thank you

**Comment by gkanishk** [comment]
Hey @chandan-kj ,
You have created multiple copy of your directory so kindly revert the duplicate one.

Also it's good @Uyadav207 is helping for the **PRs** can you DM me on Telegram @Uyadav207 .

**Pull request closed without merging**
