### PR TITLE
Simscool1/registration update

### PR DESCRIPTION
**Pull request by simscool1**
Hey Maintainer, I have done the required changes. Kindly accept my Pull request.

### CODE REVIEW

**Comment by simscool1** [comment]
> Hey Maintainer, I have done the required changes. Kindly accept my Pull request.



> Hey Maintainer, I have done the required changes. Kindly accept my Pull request.

There were some grammar errors in my index.md. I resolved it.

**Comment by gkanishk** [comment]
hey @simscool1 ,
I can still see you have done changes inside other files other than your index.md file like:
- `content/participants/ttjc@yashmantri20/index.md`
- `content/participants/ttjc@hetp97/index.md `
- `content/participants/ttjc@Pankajtanwarbanna/index.md` 
# Please tell me if you are unable to resolve I will take care of it else kindly resolve the changes

**Comment by simscool1** [comment]
> hey @simscool1 ,
> I can still see you have done changes inside files other than your index.md file like:
> 
> * `content/participants/ttjc@yashmantri20/index.md`
> * `content/participants/ttjc@hetp97/index.md `
> * `content/participants/ttjc@Pankajtanwarbanna/index.md`
> 
> # Please tell me if you are unable to resolve I will take care of it else kindly resolve the changes
> Also, make sure **files changed** shows count 1
> image

Hey Maintainer, I tried to fix it using multiple ways. But reverting was not possible as file was unmerged.I tried to merge it as well, but, could not happen. I searched, used stackoverflow, but error remained same. I know, I have messed it too much. But now, I really request you to help me to fix it.

**Comment by gkanishk** [comment]
> > hey @simscool1 ,
> > I can still see you have done changes inside files other than your index.md file like:
> > 
> > * `content/participants/ttjc@yashmantri20/index.md`
> > * `content/participants/ttjc@hetp97/index.md `
> > * `content/participants/ttjc@Pankajtanwarbanna/index.md`
> > 
> > # Please tell me if you are unable to resolve I will take care of it else kindly resolve the changes
> > Also, make sure **files changed** shows count 1
> > image
> 
> Hey Maintainer, I tried to fix it using multiple ways. But reverting was not possible as file was unmerged.I tried to merge it as well, but, could not happen. I searched, used stackoverflow, but error remained same. I know, I have messed it too much. But now, I really request you to help me to fix it.

I would suggest clone the repo again and generate the PR that will resolve the issue let me know if you are unable to do.

**Comment by simscool1** [comment]
> > > hey @simscool1 ,
> > > I can still see you have done changes inside files other than your index.md file like:
> > > 
> > > * `content/participants/ttjc@yashmantri20/index.md`
> > > * `content/participants/ttjc@hetp97/index.md `
> > > * `content/participants/ttjc@Pankajtanwarbanna/index.md`
> > > 
> > > # Please tell me if you are unable to resolve I will take care of it else kindly resolve the changes
> > > Also, make sure **files changed** shows count 1
> > > image
> > 
> > 
> > Hey Maintainer, I tried to fix it using multiple ways. But reverting was not possible as file was unmerged.I tried to merge it as well, but, could not happen. I searched, used stackoverflow, but error remained same. I know, I have messed it too much. But now, I really request you to help me to fix it.
> 
> I would suggest clone the repo again and generate the PR that will resolve the issue let me know if you are unable to do.

I cloned again and sent PR again.

**Comment by simscool1** [comment]
> > > hey @simscool1 ,
> > > I can still see you have done changes inside files other than your index.md file like:
> > > 
> > > * `content/participants/ttjc@yashmantri20/index.md`
> > > * `content/participants/ttjc@hetp97/index.md `
> > > * `content/participants/ttjc@Pankajtanwarbanna/index.md`
> > > 
> > > # Please tell me if you are unable to resolve I will take care of it else kindly resolve the changes
> > > Also, make sure **files changed** shows count 1
> > > image
> > 
> > 
> > Hey Maintainer, I tried to fix it using multiple ways. But reverting was not possible as file was unmerged.I tried to merge it as well, but, could not happen. I searched, used stackoverflow, but error remained same. I know, I have messed it too much. But now, I really request you to help me to fix it.
> 
> I would suggest clone the repo again and generate the PR that will resolve the issue let me know if you are unable to do.

Thank you for your suggestion. It worked. :) But there is one unresolved issue. File of Piyush Verma that I renamed by mistake is still renamed. How can I solve that?

**Comment by gkanishk** [comment]
> > > > hey @simscool1 ,
> > > > I can still see you have done changes inside files other than your index.md file like:
> > > > 
> > > > * `content/participants/ttjc@yashmantri20/index.md`
> > > > * `content/participants/ttjc@hetp97/index.md `
> > > > * `content/participants/ttjc@Pankajtanwarbanna/index.md`
> > > > 
> > > > # Please tell me if you are unable to resolve I will take care of it else kindly resolve the changes
> > > > Also, make sure **files changed** shows count 1
> > > > image
> > > 
> > > 
> > > Hey Maintainer, I tried to fix it using multiple ways. But reverting was not possible as file was unmerged.I tried to merge it as well, but, could not happen. I searched, used stackoverflow, but error remained same. I know, I have messed it too much. But now, I really request you to help me to fix it.
> > 
> > 
> > I would suggest clone the repo again and generate the PR that will resolve the issue let me know if you are unable to do.
> 
> Thank you for your suggestion. It worked. :) But there is one unresolved issue. File of Piyush Verma that I renamed by mistake is still renamed. How can I solve that?

Great!!
Check the repository with his name and rename accordingly 😂😂😂😂

**Comment by simscool1** [comment]
> > > > hey @simscool1 ,
> > > > I can still see you have done changes inside files other than your index.md file like:
> > > > 
> > > > * `content/participants/ttjc@yashmantri20/index.md`
> > > > * `content/participants/ttjc@hetp97/index.md `
> > > > * `content/participants/ttjc@Pankajtanwarbanna/index.md`
> > > > 
> > > > # Please tell me if you are unable to resolve I will take care of it else kindly resolve the changes
> > > > Also, make sure **files changed** shows count 1
> > > > image
> > > 
> > > 
> > > Hey Maintainer, I tried to fix it using multiple ways. But reverting was not possible as file was unmerged.I tried to merge it as well, but, could not happen. I searched, used stackoverflow, but error remained same. I know, I have messed it too much. But now, I really request you to help me to fix it.
> > 
> > 
> > I would suggest clone the repo again and generate the PR that will resolve the issue let me know if you are unable to do.
> 
> Thank you for your suggestion. It worked. :) But there is one unresolved issue. File of Piyush Verma that I renamed by mistake is still renamed. How can I solve that?

Hey Maintainer,
Number of files changed is showing count 1.
And I did some editing in my file. 
Which means, I can happily request you to merge it. Again, Sorry for the inconvenience caused by me and Thank You so much for your help.

**Comment by simscool1** [comment]
> > > > > hey @simscool1 ,
> > > > > I can still see you have done changes inside files other than your index.md file like:
> > > > > 
> > > > > * `content/participants/ttjc@yashmantri20/index.md`
> > > > > * `content/participants/ttjc@hetp97/index.md `
> > > > > * `content/participants/ttjc@Pankajtanwarbanna/index.md`
> > > > > 
> > > > > # Please tell me if you are unable to resolve I will take care of it else kindly resolve the changes
> > > > > Also, make sure **files changed** shows count 1
> > > > > image
> > > > 
> > > > 
> > > > Hey Maintainer, I tried to fix it using multiple ways. But reverting was not possible as file was unmerged.I tried to merge it as well, but, could not happen. I searched, used stackoverflow, but error remained same. I know, I have messed it too much. But now, I really request you to help me to fix it.
> > > 
> > > 
> > > I would suggest clone the repo again and generate the PR that will resolve the issue let me know if you are unable to do.
> > 
> > 
> > Thank you for your suggestion. It worked. :) But there is one unresolved issue. File of Piyush Verma that I renamed by mistake is still renamed. How can I solve that?
> 
> Hey Maintainer,
> Number of files changed is showing count 1.
> And I did some editing in my file.
> Which means, I can happily request you to merge it. Again, Sorry for the inconvenience caused by me and Thank You so much for your help.

A request, can you remove "dikkat hi dikkat" tag? Please!

**Pull request merged**
