### PR TITLE
Registering Srbhr

### PR DESCRIPTION
**Pull request by srbhr**
Changed the content and added the links. One repository is private and it's a work in progress with 40% of the work done. I've been working with it from the past two weeks.

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @srbhr ,
Projects and blogs done after mid-March 2020 are accepted for the challenge and make sure you have made it public as private ones are not accepted and should have a hosted link.

**Comment by srbhr** [comment]
Yes I've updated as you have told me @gkanishk .
I have removed those projects as of now, and I'll update them later on as part of this plan.

**Comment by gkanishk** [comment]
Hey @srbhr ,
I can still see your old projects visible, you can add them inside your portfolio.
Also, do one thing if you can't host the project then you can document them into a site and host it simply the way the projects work, that would be pretty awesome and eye-catching. 
Best,
Kanishk

**Comment by srbhr** [comment]
Well I'm trying to make a unifying UI for all my ML Apps so that I can showcase them or put them in a better presentable manner. Thanks for the tip.
Have a nice day @gkanishk ,
srbhr, (discord: flammie)

**Pull request closed without merging**
