### PR TITLE
registering mandeepPanwar

### PR DESCRIPTION
**Pull request by mannypanwar**
Hii amazing maintainer on the internet!

We appreciate your work, Kindly accept my request

### CODE REVIEW

**Comment by gkanishk** [comment]
The **first round** of registrations are closed and hence we are not accepting this **PR** right now. Stay tuned for further updates on [t.me/tanaypratap](t.me/tanaypratap) and apply again when the registration re-opens in a few days. This PR might not be considered for that round or will be considered only at the end. Therefore, it would be better to raise a fresh PR when the registration announcement is made.

**Comment by mannypanwar** [comment]
Ok Kanishk, Will surely apply for next round. **Thanks for your time**💙

**Comment by gkanishk** [comment]
@mannypanwar can you confirm if your **PR** is accepted then please close this one

**Comment by gkanishk** [comment]
Already registered

**Pull request closed without merging**
