### PR TITLE
Registering amarcahturvedi16

### PR DESCRIPTION
**Pull request by amarcahturvedi16**
Hello maintainer, 
Thank you so much for this opportunity.

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @amarcahturvedi16  ,
I just reviewed your **PR** and noticed you did everything the **wrong** way.
You have done changes is wrong to file you need to create a new directory with your username and put an **index.md** file with your details
This is how it would look like:
image
Kindly refer to the [Youtube Live](https://www.youtube.com/watch?v=QzjgBj9oaAA&t=850s) for the correct way.

**Comment by amarcahturvedi16** [comment]
Hi maintainer,
Rather than cloning the repository and making changes to that, I mistakenly deleted that repository.
Have raised a me a PR #80 is the mine .
Can you please review is and label is as good to merge if possible.

**Comment by gkanishk** [comment]
Please close this pr have reviewed the other one

**Comment by amarcahturvedi16** [comment]
Thank you so much sir.

**Pull request closed without merging**
