### PR TITLE
Registering JaynilGaglani

### PR DESCRIPTION
**Pull request by Jaynil1611**
Thank You!

### CODE REVIEW

**Comment by khusharth** [comment]
Hey! @Jaynil1611  the project and blog that you have added have been built before the start of the challenge. Only projects and blogs made during the challenge are counted towards the challenge. If you want to add previous projects then specify them as past projects in this file.

**Comment by Jaynil1611** [comment]
> Hey! @Jaynil1611 the project and blog that you have added have been built before the start of the challenge. Only projects and blogs made during the challenge are counted towards the challenge. If you want to add previous projects then specify them as past projects in this file.

I have updated the projects as past projects and removed the blog.

**Comment by khusharth** [comment]
Hey! @Jaynil1611 sorry for the inconvenience but we have decided not to keep the past projects in the index.md file. Please remove them and your PR will be merged.

**Comment by Jaynil1611** [comment]
> Hey! @Jaynil1611 sorry for the inconvenience but we have decided not to keep the past projects in the index.md file. Please remove them and your PR will be merged.

Done.

**Pull request merged**
