### PR TITLE
portfolio update

### PR DESCRIPTION
**Pull request by singularityDev**
I had to create another branch after I messed up the steps to create PR on previous branch,
content is the same though. TIA.

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @singularityDev ,
There are some conflict in your PR can you please resolve them

**Comment by singularityDev** [comment]
> Hey @singularityDev ,
> There are some conflict in your PR can you please resolve them

I'll look into it, thanks 😃

**Comment by singularityDev** [comment]
I have checked the conflicts and kept what is required, yet it says that there are conflicts. Could you please guide me how to resolve the conflicts that you see now. TIA

**Comment by gkanishk** [comment]
There are conflicts inside ttjc@singularityDev/index.md and package.json files try to replace them with original files and conflicts will be resolved

**Comment by singularityDev** [comment]
> There are conflicts inside ttjc@singularityDev/index.md and package.json files try to replace them with original files and conflicts will be resolved

Gotcha, Thanks!

**Comment by singularityDev** [comment]
Can you please me what's happening with my PR?
I have rebased the origin and tried to resolve the conflicts but this still has conflicts...

**Comment by gkanishk** [comment]
There are still some conflicts resolve it else or generate a fresh PR

**Comment by singularityDev** [comment]
mmm, I'll try one more time then I'll do a new PR.

**Comment by gkanishk** [comment]
you have done changes inside your index.md file that's having some conflicts

**Comment by gkanishk** [comment]
great !!

**Comment by singularityDev** [comment]
I have stashed, popped and added the files before committing it...

**Comment by gkanishk** [comment]
follow the resolve conflicts instruction that will help

**Comment by gkanishk** [comment]
closing this as have merged #306

**Pull request closed without merging**
