### PR TITLE
Syedsufiyan/ portfolio

### PR DESCRIPTION
**Pull request by thesyedsufiyan**

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @thesyedsufiyan ,
Can you add descriptions for your blogs and kindly remove the comments at the end of the file.

**Comment by thesyedsufiyan** [comment]
i will do it right away

**Comment by thesyedsufiyan** [comment]
@gkanishk is it fine

**Comment by gkanishk** [comment]
Perfect!!
Now you can raise a **PR** for the finalist.

**Comment by thesyedsufiyan** [comment]
@gkanishk i am not getting finalist page, please help

**Comment by thesyedsufiyan** [comment]
@gkanishk  finalist directory is not present in my ide

**Pull request merged**
