### PR TITLE
Registering vedantk21

### PR DESCRIPTION
**Pull request by vedantk21**
Hey maintainer, you're doing a great job. Kindly accept my request :)

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @vedantk21 kindly revert the changes inside multiple files and do changes only in index.md file

**Comment by vedantk21** [comment]
Didn't make any changes intentionally before.
Couldn't figure out how to undo the unrequired changes , deleted them instead but this lead to more problems :( @gkanishk

**Comment by gkanishk** [comment]
You don't need to delete the files simply see what were the changes done like any addition any removal or change in the indentation.

**Comment by vedantk21** [comment]
All unnecessary, unintentional changes reverted, kindly check.
Thank you :)

**Pull request merged**
