### PR TITLE
Blog 2

### PR DESCRIPTION
**Pull request by vinaysharmatech**
Admin, the last PR for this challenge.

### CODE REVIEW

**Comment by gkanishk** [comment]
Not completed 5 projects why??????

**Comment by vinaysharmatech** [comment]
I started late kanishk & good projects [zero to one] need a month.

**Comment by gkanishk** [comment]
Cool not an issue please make your site responsive
image
You have used GraphQl that's really awesome!!

**Comment by vinaysharmatech** [comment]
Thanks. "ll rectify it.

**Pull request merged**
