### PR TITLE
Your GitHub id/registration update

### PR DESCRIPTION
**Pull request by Mojojojooo**

### CODE REVIEW

**Comment by Mojojojooo** [comment]
How to merge

**Comment by Mojojojooo** [comment]
Hello !
Can you merge this part.

**Comment by khusharth** [comment]
Hey! @Mojojojooo i can see you have made changes in 4 files. Only changes done in your own **index.md** file are allowed. Please revert them.

**Comment by Mojojojooo** [comment]
Actually I made changes only in the index.md file. I will look into it may be VS code file got commited.

**Comment by Mojojojooo** [comment]
Hey ! 
I have reverted them requesting you to please check and merge it.

**Comment by gkanishk** [comment]
Hey @Mojojojooo ,
I like you username Mojojojooo powerpuff girl fan??
As @khusharth mentioned you have done changes inside multuple file i.e.
image
- There are some bin files created kindly remove them maybe they are not visible so find them and remove
- Also you have mentioned some of your projects so make sure you provide individual 
  - description
  - Hosted link
  - source code
  - and most important projects should have been made after **mid-March 2020**

**Comment by Mojojojooo** [comment]
I tried but could not find the files so I deleted and will clone it again.

**Pull request closed without merging**
