### PR TITLE
registering 4k45hv3rm4

### PR DESCRIPTION
**Pull request by 4k45hv3rm4**
**Hello mentors , please accept my request !!!**

### CODE REVIEW

**Comment by gkanishk** [comment]
Hey @4k45hv3rm4   ,
I just reviewed your **PR** and noticed you did everything the **wrong** way.
You have done changes in **package-lock.json** file and have deleted some of the sections,
Make sure you don't do any changes in any other file other than **index.md** file as follows:
image

Kindly refer to the [Youtube Live](https://www.youtube.com/watch?v=QzjgBj9oaAA&t=850s) for the correct way.

**Comment by gkanishk** [comment]
There's still an issue, make sure file changes show only 1 ,if your not able to resolve then maintainers will resolve

**Comment by gkanishk** [comment]
There's a space added at line 1751

**Comment by 4k45hv3rm4** [comment]
hey @gkanishk ,  I have removed that space .

**Pull request merged**
